-- MySQL Script generated by MySQL Workbench
-- Sun Mar 10 14:24:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema defaultdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema defaultdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `defaultdb` DEFAULT CHARACTER SET utf8 ;
USE `defaultdb` ;

-- -----------------------------------------------------
-- Table `defaultdb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `defaultdb`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `defaultdb`.`servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`servico` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`servico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `preco` FLOAT NULL,
  `img` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `defaultdb`.`carro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`carro` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`carro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `modelo` VARCHAR(200) NOT NULL,
  `descricao` TEXT NULL,
  `img` VARCHAR(300) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `defaultdb`.`contrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`contrato` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`contrato` (
  `Cliente_id` INT NOT NULL,
  `servico_id` INT NOT NULL,
  `carro_id` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `forma_pagamento` VARCHAR(100) NOT NULL,
  `confirmacao_pagamento` TINYINT NOT NULL DEFAULT 0,
  `desconto` FLOAT NOT NULL,
  `aprovado` TINYINT NOT NULL DEFAULT 0,
  `Funcionario_id` INT NULL,
  PRIMARY KEY (`Cliente_id`, `servico_id`, `carro_id`),
  INDEX `fk_contrato_servico1_idx` (`servico_id` ASC) VISIBLE,
  INDEX `fk_contrato_carro1_idx` (`carro_id` ASC) VISIBLE,
  INDEX `fk_contrato_Funcionario1_idx` (`Funcionario_id` ASC) VISIBLE,
  CONSTRAINT `fk_contrato_Cliente`
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `defaultdb`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_servico1`
    FOREIGN KEY (`servico_id`)
    REFERENCES `defaultdb`.`servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_carro1`
    FOREIGN KEY (`carro_id`)
    REFERENCES `defaultdb`.`carro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_Funcionario1`
    FOREIGN KEY (`Funcionario_id`)
    REFERENCES `defaultdb`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
